# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]

env:
  NEXT_PUBLIC_BASE_PATH: /blog
  NEXT_PUBLIC_PROD_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_PROD_FIREBASE_API_KEY }}
  NEXT_PUBLIC_PROD_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_PROD_FIREBASE_AUTH_DOMAIN }}
  NEXT_PUBLIC_PROD_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_PROD_FIREBASE_PROJECT_ID }}
  NEXT_PUBLIC_PROD_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_PROD_FIREBASE_STORAGE_BUCKET }}
  NEXT_PUBLIC_PROD_FIREBASE_MS_ID: ${{ secrets.NEXT_PUBLIC_PROD_FIREBASE_MS_ID }}
  NEXT_PUBLIC_PROD_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_PROD_FIREBASE_APP_ID }}
  NEXT_PUBLIC_PROD_FIREBASE_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_PROD_FIREBASE_MEASUREMENT_ID }}

jobs:
  build:


    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: touch ./out/.nojekyll

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: out # The folder the action should deploy.
